### ISSUE TITLE
Mapa mental conjuntos y relaciones 

### ISSUE THREAD

**Issue by irwingsael** [SistemasTecTlaxiaco/actividad-4-mapa-mental-irwingsael#2]
[Conjuntos y relaciones .pdf](https://github.com/user-attachments/files/17080014/Conjuntos.y.relaciones.pdf)

**Comment by Evelyn-sj13** [comment]
Exposición de Ideas Centrales:5/5
Redacción y Ortografía:5/5
Presentación visual:4/5
Referencias:5/5
Calificación Final:19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
